CREATE TABLE IF NOT EXISTS `fl_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `task_type` VARCHAR(32) NOT NULL,
  `dataset_name` VARCHAR(128) DEFAULT NULL,
  `dataset_path` VARCHAR(512) NOT NULL,
  `dataset_format` VARCHAR(32) DEFAULT NULL,
  `model_source` VARCHAR(512) DEFAULT NULL,
  `num_rounds` INT DEFAULT NULL,
  `node_count` INT DEFAULT NULL,
  `current_round` INT DEFAULT 0,
  `local_epochs` INT DEFAULT NULL,
  `batch_size` INT DEFAULT NULL,
  `learning_rate` DECIMAL(16,8) DEFAULT NULL,
  `fraction_evaluate` DECIMAL(10,4) DEFAULT NULL,
  `final_metric_name` VARCHAR(64) DEFAULT NULL,
  `final_metric_value` DECIMAL(16,8) DEFAULT NULL,
  `latest_metrics_json` LONGTEXT DEFAULT NULL,
  `final_metrics_json` LONGTEXT DEFAULT NULL,
  `work_dir` VARCHAR(512) DEFAULT NULL,
  `final_model_path` VARCHAR(512) DEFAULT NULL,
  `error_message` VARCHAR(1000) DEFAULT NULL,
  `config_json` LONGTEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `started_at` DATETIME DEFAULT NULL,
  `finished_at` DATETIME DEFAULT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fl_task_task_id` (`task_id`),
  KEY `idx_fl_task_status` (`status`),
  KEY `idx_fl_task_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `fl_task_round_metric` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(64) NOT NULL,
  `round_no` INT NOT NULL,
  `loss` DECIMAL(16,8) DEFAULT NULL,
  `primary_metric` DECIMAL(16,8) DEFAULT NULL,
  `metrics_json` LONGTEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_fl_task_round` (`task_id`, `round_no`),
  KEY `idx_fl_task_round_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
