/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "exception": "/exception";
    "exception_403": "/exception/403";
    "exception_404": "/exception/404";
    "exception_500": "/exception/500";
    "document": "/document";
    "document_project": "/document/project";
    "document_project-link": "/document/project-link";
    "document_vue": "/document/vue";
    "document_vite": "/document/vite";
    "document_unocss": "/document/unocss";
    "document_naive": "/document/naive";
    "document_antd": "/document/antd";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "boxpulse": "/boxpulse";
    "boxpulse_code-test": "/boxpulse/code-test";
    "boxpulse_test": "/boxpulse/test";
    "data-ano": "/data-ano";
    "data-ano_autoano": "/data-ano/autoano";
    "data-ano_detail": "/data-ano/detail";
    "data-ano_group": "/data-ano/group";
    "data-ano_groupmanage": "/data-ano/groupmanage";
    "data-ano_gtag": "/data-ano/gtag";
    "data-ano_imgoperate": "/data-ano/imgoperate";
    "data-ano_mulano": "/data-ano/mulano";
    "data-ano_mulanotask": "/data-ano/mulanotask";
    "data-ano_online": "/data-ano/online";
    "data-ano_operation": "/data-ano/operation";
    "data-expansion": "/data-expansion";
    "data-expansion_add": "/data-expansion/add";
    "data-expansion_addmap": "/data-expansion/addmap";
    "data-expansion_errarea": "/data-expansion/errarea";
    "data-expansion_exportres": "/data-expansion/exportres";
    "data-expansion_extend": "/data-expansion/extend";
    "data-expansion_imgopmaster": "/data-expansion/imgopmaster";
    "data-expansion_imgtask": "/data-expansion/imgtask";
    "data-expansion_scenechange": "/data-expansion/scenechange";
    "data-manage": "/data-manage";
    "data-manage_detail": "/data-manage/detail";
    "data-manage_export": "/data-manage/export";
    "data-manage_import": "/data-manage/import";
    "data-manage_list": "/data-manage/list";
    "data-manage_map": "/data-manage/map";
    "data-manage_maplist": "/data-manage/maplist";
    "data-manage_operation": "/data-manage/operation";
    "dataset": "/dataset";
    "dataset_operate": "/dataset/operate";
    "dataset_taggroupmanager": "/dataset/taggroupmanager";
    "federated-learning": "/federated-learning";
    "home": "/home";
    "login": "/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?";
    "manage": "/manage";
    "manage_dept": "/manage/dept";
    "manage_dict": "/manage/dict";
    "manage_dict-type": "/manage/dict-type";
    "manage_log": "/manage/log";
    "manage_log_login": "/manage/log/login";
    "manage_log_operate": "/manage/log/operate";
    "manage_menu": "/manage/menu";
    "manage_modelconfig": "/manage/modelconfig";
    "manage_role": "/manage/role";
    "manage_user": "/manage/user";
    "manage_user-detail": "/manage/user-detail/:id";
    "model": "/model";
    "model_create": "/model/create";
    "model_info": "/model/info";
    "model-distillation": "/model-distillation";
    "model-manage": "/model-manage";
    "model-manage_assess": "/model-manage/assess";
    "model-manage_config": "/model-manage/config";
    "model-manage_createtask": "/model-manage/createtask";
    "model-manage_default": "/model-manage/default";
    "model-manage_federated": "/model-manage/federated";
    "model-manage_prevassess": "/model-manage/prevassess";
    "model-manage_prevassessoperate": "/model-manage/prevassessoperate";
    "model-manage_thirdpartyevaluation": "/model-manage/thirdpartyevaluation";
    "model-manage_thirdpartymodel": "/model-manage/thirdpartymodel";
    "model-manage_train": "/model-manage/train";
    "target-monitor": "/target-monitor";
    "target-monitor_modelinference": "/target-monitor/modelinference";
    "thirdparty": "/thirdparty";
    "thirdparty_approve": "/thirdparty/approve";
    "thirdparty_assess": "/thirdparty/assess";
    "thirdparty_createtask": "/thirdparty/createtask";
    "thirdparty_info": "/thirdparty/info";
    "thirdparty_model": "/thirdparty/model";
    "thirdparty_modelmanage": "/thirdparty/modelmanage";
    "thirdparty_modeloperate": "/thirdparty/modeloperate";
    "thirdparty_operate": "/thirdparty/operate";
    "thirdparty_prevassess": "/thirdparty/prevassess";
    "thirdparty_report": "/thirdparty/report";
    "thirdparty_test": "/thirdparty/test";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "boxpulse"
    | "data-ano"
    | "data-expansion"
    | "data-manage"
    | "dataset"
    | "federated-learning"
    | "home"
    | "login"
    | "manage"
    | "model"
    | "model-distillation"
    | "model-manage"
    | "target-monitor"
    | "thirdparty"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception"
    | "document"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "boxpulse_code-test"
    | "boxpulse_test"
    | "thirdparty_approve"
    | "thirdparty_assess"
    | "thirdparty_createtask"
    | "thirdparty_info"
    | "thirdparty_model"
    | "thirdparty_modelmanage"
    | "thirdparty_modeloperate"
    | "thirdparty_operate"
    | "thirdparty_prevassess"
    | "thirdparty_report"
    | "thirdparty_test"
    | "403"
    | "404"
    | "500"
    | "login"
    | "data-ano_autoano"
    | "data-ano_detail"
    | "data-ano_gtag"
    | "data-ano_group"
    | "data-ano_groupmanage"
    | "data-ano_imgoperate"
    | "data-ano_mulano"
    | "data-ano_mulanotask"
    | "data-ano_online"
    | "data-ano_operation"
    | "data-expansion_imgopmaster"
    | "data-expansion_add"
    | "data-expansion_addmap"
    | "data-expansion_errarea"
    | "data-expansion_exportres"
    | "data-expansion_extend"
    | "data-expansion_imgtask"
    | "data-expansion_scenechange"
    | "data-manage_detail"
    | "data-manage_export"
    | "data-manage_import"
    | "data-manage_list"
    | "data-manage_map"
    | "data-manage_maplist"
    | "data-manage_operation"
    | "dataset_taggroupmanager"
    | "dataset_operate"
    | "federated-learning"
    | "home"
    | "manage_dept"
    | "manage_dict-type"
    | "manage_dict"
    | "manage_log_login"
    | "manage_log_operate"
    | "manage_menu"
    | "manage_modelconfig"
    | "manage_role"
    | "manage_user-detail"
    | "manage_user"
    | "model-distillation"
    | "model-manage_thirdpartyevaluation"
    | "model-manage_thirdpartymodel"
    | "model-manage_assess"
    | "model-manage_config"
    | "model-manage_createtask"
    | "model-manage_default"
    | "model-manage_federated"
    | "model-manage_prevassess"
    | "model-manage_prevassessoperate"
    | "model-manage_train"
    | "model_create"
    | "model_info"
    | "target-monitor_modelinference"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
    | "exception_403"
    | "exception_404"
    | "exception_500"
    | "document_project"
    | "document_project-link"
    | "document_vue"
    | "document_vite"
    | "document_unocss"
    | "document_naive"
    | "document_antd"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;
  
  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;
  
  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
