/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'boxpulse',
    path: '/boxpulse',
    component: 'layout.base',
    meta: {
      title: 'boxpulse',
      i18nKey: 'route.boxpulse',
      localIcon: 'boxpulse',
      order: 7
    },
    children: [
      {
        name: 'boxpulse_code-test',
        path: '/boxpulse/code-test',
        component: 'view.boxpulse_code-test',
        meta: {
          title: 'boxpulse_code-test',
          i18nKey: 'route.boxpulse_code-test',
          localIcon: 'boxpulse_code-test'
        }
      },
      {
        name: 'boxpulse_test',
        path: '/boxpulse/test',
        component: 'view.boxpulse_test',
        meta: {
          title: 'boxpulse_test',
          i18nKey: 'route.boxpulse_test',
          localIcon: 'boxpulse_test'
        }
      }
    ]
  },
  {
    name: 'data-ano',
    path: '/data-ano',
    component: 'layout.base',
    meta: {
      title: 'data-ano',
      i18nKey: 'route.data-ano',
      order: 3,
      icon: 'pajamas:labels',
      localIcon: 'pajamas--labels'
    },
    children: [
      {
        name: 'data-ano_autoano',
        path: '/data-ano/autoano',
        component: 'view.data-ano_autoano',
        meta: {
          title: 'data-ano_autoano',
          i18nKey: 'route.data-ano_autoano',
          localIcon: 'ic--baseline-auto-graph',
          order: 3,
          hideInMenu: false
        }
      },
      {
        name: 'data-ano_detail',
        path: '/data-ano/detail',
        component: 'view.data-ano_detail',
        meta: {
          title: 'data-ano_detail',
          i18nKey: 'route.data-ano_detail',
          hideInMenu: true,
          icon: '',
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-ano_group',
        path: '/data-ano/group',
        component: 'view.data-ano_group',
        meta: {
          title: 'data-ano_group',
          i18nKey: 'route.data-ano_group',
          icon: 'material-symbols-light:ad-group',
          localIcon: 'material-symbols--ad-group'
        }
      },
      {
        name: 'data-ano_groupmanage',
        path: '/data-ano/groupmanage',
        component: 'view.data-ano_groupmanage',
        meta: {
          title: 'data-ano_groupmanage',
          i18nKey: 'route.data-ano_groupmanage',
          hideInMenu: true,
          localIcon: 'data-ano_groupManage',
          activeMenu: 'data-ano_mulano'
        }
      },
      {
        name: 'data-ano_gtag',
        path: '/data-ano/gtag',
        component: 'view.data-ano_gtag',
        meta: {
          title: 'data-ano_gtag',
          i18nKey: 'route.data-ano_gtag',
          hideInMenu: true,
          activeMenu: 'data-ano_group',
          icon: ''
        }
      },
      {
        name: 'data-ano_imgoperate',
        path: '/data-ano/imgoperate',
        component: 'view.data-ano_imgoperate',
        meta: {
          title: 'data-ano_imgoperate',
          i18nKey: 'route.data-ano_imgoperate',
          localIcon: 'ep--operation',
          hideInMenu: true,
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-ano_mulano',
        path: '/data-ano/mulano',
        component: 'view.data-ano_mulano',
        meta: {
          title: 'data-ano_mulano',
          i18nKey: 'route.data-ano_mulano',
          localIcon: 'data-ano_mulano',
          order: 6
        }
      },
      {
        name: 'data-ano_mulanotask',
        path: '/data-ano/mulanotask',
        component: 'view.data-ano_mulanotask',
        meta: {
          title: 'data-ano_mulanotask',
          i18nKey: 'route.data-ano_mulanotask',
          hideInMenu: true,
          localIcon: 'data-ano_mulTask',
          activeMenu: 'data-ano_mulano'
        }
      },
      {
        name: 'data-ano_online',
        path: '/data-ano/online',
        component: 'view.data-ano_online',
        meta: {
          title: 'data-ano_online',
          i18nKey: 'route.data-ano_online',
          icon: 'pajamas:label',
          localIcon: 'ic--baseline-label'
        }
      },
      {
        name: 'data-ano_operation',
        path: '/data-ano/operation',
        component: 'view.data-ano_operation',
        meta: {
          title: 'data-ano_operation',
          i18nKey: 'route.data-ano_operation',
          hideInMenu: true,
          icon: '',
          localIcon: 'ep--operation',
          activeMenu: 'data-manage_maplist'
        }
      }
    ]
  },
  {
    name: 'data-expansion',
    path: '/data-expansion',
    component: 'layout.base',
    meta: {
      title: 'data-expansion',
      i18nKey: 'route.data-expansion',
      order: 6,
      icon: 'material-symbols:folder-data',
      localIcon: 'icon-park-outline--internal-expansion'
    },
    children: [
      {
        name: 'data-expansion_add',
        path: '/data-expansion/add',
        component: 'view.data-expansion_add',
        meta: {
          title: 'data-expansion_add',
          i18nKey: 'route.data-expansion_add',
          icon: 'mdi:train-crossing-light',
          localIcon: 'mdi--train-crossing-light',
          hideInMenu: true
        }
      },
      {
        name: 'data-expansion_addmap',
        path: '/data-expansion/addmap',
        component: 'view.data-expansion_addmap',
        meta: {
          title: 'data-expansion_addmap',
          i18nKey: 'route.data-expansion_addmap',
          icon: '',
          hideInMenu: true
        }
      },
      {
        name: 'data-expansion_errarea',
        path: '/data-expansion/errarea',
        component: 'view.data-expansion_errarea',
        meta: {
          title: 'data-expansion_errarea',
          i18nKey: 'route.data-expansion_errarea',
          icon: 'icon-park-outline:area-map',
          localIcon: 'icon-park-outline--area-map'
        }
      },
      {
        name: 'data-expansion_exportres',
        path: '/data-expansion/exportres',
        component: 'view.data-expansion_exportres',
        meta: {
          title: 'data-expansion_exportres',
          i18nKey: 'route.data-expansion_exportres',
          icon: '',
          hideInMenu: true
        }
      },
      {
        name: 'data-expansion_extend',
        path: '/data-expansion/extend',
        component: 'view.data-expansion_extend',
        meta: {
          title: 'data-expansion_extend',
          i18nKey: 'route.data-expansion_extend',
          order: 5
        }
      },
      {
        name: 'data-expansion_imgopmaster',
        path: '/data-expansion/imgopmaster',
        component: 'view.data-expansion_imgopmaster',
        meta: {
          title: 'data-expansion_imgopmaster',
          i18nKey: 'route.data-expansion_imgopmaster',
          localIcon: 'ImgOpMaster',
          order: 3
        }
      },
      {
        name: 'data-expansion_imgtask',
        path: '/data-expansion/imgtask',
        component: 'view.data-expansion_imgtask',
        meta: {
          title: 'data-expansion_imgtask',
          i18nKey: 'route.data-expansion_imgtask',
          localIcon: 'data-expansion_imgTask',
          hideInMenu: true,
          activeMenu: 'data-expansion_imgopmaster'
        }
      },
      {
        name: 'data-expansion_scenechange',
        path: '/data-expansion/scenechange',
        component: 'view.data-expansion_scenechange',
        meta: {
          title: 'data-expansion_scenechange',
          i18nKey: 'route.data-expansion_scenechange',
          icon: 'icon-park:change',
          localIcon: 'icon-park--change'
        }
      }
    ]
  },
  {
    name: 'data-manage',
    path: '/data-manage',
    component: 'layout.base',
    meta: {
      title: 'data-manage',
      i18nKey: 'route.data-manage',
      order: 2,
      icon: 'bxs:data',
      localIcon: 'bxs--data'
    },
    children: [
      {
        name: 'data-manage_detail',
        path: '/data-manage/detail',
        component: 'view.data-manage_detail',
        meta: {
          title: 'data-manage_detail',
          i18nKey: 'route.data-manage_detail',
          icon: '',
          hideInMenu: true,
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-manage_export',
        path: '/data-manage/export',
        component: 'view.data-manage_export',
        meta: {
          title: 'data-manage_export',
          i18nKey: 'route.data-manage_export',
          hideInMenu: true,
          icon: '',
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-manage_import',
        path: '/data-manage/import',
        component: 'view.data-manage_import',
        meta: {
          title: 'data-manage_import',
          i18nKey: 'route.data-manage_import',
          hideInMenu: true,
          icon: '',
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-manage_list',
        path: '/data-manage/list',
        component: 'view.data-manage_list',
        meta: {
          title: 'data-manage_list',
          i18nKey: 'route.data-manage_list',
          hideInMenu: true,
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'data-manage_map',
        path: '/data-manage/map',
        component: 'view.data-manage_map',
        meta: {
          title: 'data-manage_map',
          i18nKey: 'route.data-manage_map',
          icon: 'material-symbols-light:dataset-sharp',
          localIcon: 'material-symbols-light--dataset-sharp',
          activeMenu: 'data-manage_maplist',
          hideInMenu: true
        }
      },
      {
        name: 'data-manage_maplist',
        path: '/data-manage/maplist',
        component: 'view.data-manage_maplist',
        meta: {
          title: 'data-manage_maplist',
          i18nKey: 'route.data-manage_maplist',
          localIcon: 'material-symbols-light--dataset-sharp',
          hideInMenu: false
        }
      },
      {
        name: 'data-manage_operation',
        path: '/data-manage/operation',
        component: 'view.data-manage_operation',
        meta: {
          title: 'data-manage_operation',
          i18nKey: 'route.data-manage_operation',
          icon: '',
          hideInMenu: true,
          activeMenu: 'data-manage_maplist'
        }
      }
    ]
  },
  {
    name: 'dataset',
    path: '/dataset',
    component: 'layout.base',
    meta: {
      title: 'dataset',
      i18nKey: 'route.dataset',
      hideInMenu: true
    },
    children: [
      {
        name: 'dataset_operate',
        path: '/dataset/operate',
        component: 'view.dataset_operate',
        meta: {
          title: 'dataset_operate',
          i18nKey: 'route.dataset_operate',
          activeMenu: 'data-manage_maplist'
        }
      },
      {
        name: 'dataset_taggroupmanager',
        path: '/dataset/taggroupmanager',
        component: 'view.dataset_taggroupmanager',
        meta: {
          title: 'dataset_taggroupmanager',
          i18nKey: 'route.dataset_taggroupmanager',
          activeMenu: 'data-manage_maplist',
          hideInMenu: true
        }
      }
    ]
  },
  {
    name: 'federated-learning',
    path: '/federated-learning',
    component: 'layout.base$view.federated-learning',
    meta: {
      title: '联邦学习',
      i18nKey: 'route.federated-learning',
      icon: 'carbon:machine-learning-model',
      order: 8
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      localIcon: 'mdi--monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      icon: 'carbon:cloud-service-management',
      localIcon: 'carbon--cloud-service-management',
      order: 9
    },
    children: [
      {
        name: 'manage_dept',
        path: '/manage/dept',
        component: 'view.manage_dept',
        meta: {
          title: 'manage_dept',
          i18nKey: 'route.manage_dept',
          icon: 'mingcute:department-fill',
          localIcon: 'mingcute--department-fill'
        }
      },
      {
        name: 'manage_dict',
        path: '/manage/dict',
        component: 'view.manage_dict',
        meta: {
          title: 'manage_dict',
          i18nKey: 'route.manage_dict',
          icon: 'material-symbols:dictionary',
          localIcon: 'material-symbols--dictionary'
        }
      },
      {
        name: 'manage_dict-type',
        path: '/manage/dict-type',
        component: 'view.manage_dict-type',
        meta: {
          title: 'manage_dict-type',
          i18nKey: 'route.manage_dict-type',
          icon: '',
          hideInMenu: true,
          activeMenu: 'manage_dict'
        }
      },
      {
        name: 'manage_log',
        path: '/manage/log',
        meta: {
          title: 'manage_log',
          i18nKey: 'route.manage_log',
          icon: 'pajamas:log',
          localIcon: 'pajamas--log'
        },
        children: [
          {
            name: 'manage_log_login',
            path: '/manage/log/login',
            component: 'view.manage_log_login',
            meta: {
              title: 'manage_log_login',
              i18nKey: 'route.manage_log_login',
              icon: 'ic:round-login',
              localIcon: 'ic--round-login'
            }
          },
          {
            name: 'manage_log_operate',
            path: '/manage/log/operate',
            component: 'view.manage_log_operate',
            meta: {
              title: 'manage_log_operate',
              i18nKey: 'route.manage_log_operate',
              icon: 'tdesign:cooperate',
              localIcon: 'tdesign--cooperate'
            }
          }
        ]
      },
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          icon: 'material-symbols:route',
          localIcon: 'material-symbols--route',
          order: 3,
          keepAlive: true,
          hideInMenu: true
        }
      },
      {
        name: 'manage_modelconfig',
        path: '/manage/modelconfig',
        component: 'view.manage_modelconfig',
        meta: {
          title: 'manage_modelconfig',
          i18nKey: 'route.manage_modelconfig',
          icon: 'octicon:ai-model-16',
          localIcon: 'octicon--ai-model-16',
          order: 1
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          icon: 'carbon:user-role',
          localIcon: 'carbon--user-role',
          order: 2
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          icon: 'mdi:user',
          localIcon: 'mdi--user',
          order: 1
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        props: true,
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail',
          hideInMenu: true,
          activeMenu: 'manage_user'
        }
      }
    ]
  },
  {
    name: 'model',
    path: '/model',
    component: 'layout.base',
    meta: {
      title: 'model',
      i18nKey: 'route.model',
      hideInMenu: true
    },
    children: [
      {
        name: 'model_create',
        path: '/model/create',
        component: 'view.model_create',
        meta: {
          title: 'model_create',
          i18nKey: 'route.model_create',
          hideInMenu: true,
          activeMenu: 'model-manage_thirdpartymodel'
        }
      },
      {
        name: 'model_info',
        path: '/model/info',
        component: 'view.model_info',
        meta: {
          title: 'model_info',
          i18nKey: 'route.model_info',
          hideInMenu: true,
          activeMenu: 'model-manage_thirdpartyevaluation'
        }
      }
    ]
  },
  {
    name: 'model-distillation',
    path: '/model-distillation',
    component: 'layout.base$view.model-distillation',
    meta: {
      title: '大小模型协同训练',
      i18nKey: 'route.model-distillation',
      icon: 'carbon:model',
      order: 10
    }
  },
  {
    name: 'model-manage',
    path: '/model-manage',
    component: 'layout.base',
    meta: {
      title: 'model-manage',
      i18nKey: 'route.model-manage',
      icon: 'carbon:model',
      localIcon: 'carbon--model',
      order: 6,
      hideInMenu: false
    },
    children: [
      {
        name: 'model-manage_assess',
        path: '/model-manage/assess',
        component: 'view.model-manage_assess',
        meta: {
          title: 'model-manage_assess',
          i18nKey: 'route.model-manage_assess',
          localIcon: 'ic--baseline-assessment',
          order: 4
        }
      },
      {
        name: 'model-manage_config',
        path: '/model-manage/config',
        component: 'view.model-manage_config',
        meta: {
          title: 'model-manage_config',
          i18nKey: 'route.model-manage_config',
          hideInMenu: true,
          activeMenu: 'model-manage_train',
          order: 2
        }
      },
      {
        name: 'model-manage_createtask',
        path: '/model-manage/createtask',
        component: 'view.model-manage_createtask',
        meta: {
          title: 'model-manage_createtask',
          i18nKey: 'route.model-manage_createtask',
          hideInMenu: true,
          activeMenu: 'model-manage_thirdpartyevaluation'
        }
      },
      {
        name: 'model-manage_default',
        path: '/model-manage/default',
        component: 'view.model-manage_default',
        meta: {
          title: 'model-manage_default',
          i18nKey: 'route.model-manage_default',
          icon: 'octicon:ai-model-16',
          localIcon: 'octicon--ai-model-16',
          order: 1
        }
      },
      {
        name: 'model-manage_federated',
        path: '/model-manage/federated',
        component: 'view.model-manage_federated',
        meta: {
          title: 'model-manage_federated',
          i18nKey: 'route.model-manage_federated',
          order: 6
        }
      },
      {
        name: 'model-manage_prevassess',
        path: '/model-manage/prevassess',
        component: 'view.model-manage_prevassess',
        meta: {
          title: 'model-manage_prevassess',
          i18nKey: 'route.model-manage_prevassess',
          localIcon: 'model-manage_prevAssess',
          order: 3,
          hideInMenu: true
        }
      },
      {
        name: 'model-manage_prevassessoperate',
        path: '/model-manage/prevassessoperate',
        component: 'view.model-manage_prevassessoperate',
        meta: {
          title: 'model-manage_prevassessoperate',
          i18nKey: 'route.model-manage_prevassessoperate',
          activeMenu: 'thirdparty_prevassess',
          localIcon: '',
          hideInMenu: true
        }
      },
      {
        name: 'model-manage_thirdpartyevaluation',
        path: '/model-manage/thirdpartyevaluation',
        component: 'view.model-manage_thirdpartyevaluation',
        meta: {
          hideInMenu: true,
          title: 'model-manage_thirdpartyevaluation',
          i18nKey: 'route.model-manage_thirdpartyevaluation',
          order: 5,
          localIcon: 'fluent-mdl2--assessment-group-template'
        }
      },
      {
        name: 'model-manage_thirdpartymodel',
        path: '/model-manage/thirdpartymodel',
        component: 'view.model-manage_thirdpartymodel',
        meta: {
          hideInMenu: true,
          title: 'model-manage_thirdpartymodel',
          i18nKey: 'route.model-manage_thirdpartymodel',
          order: 4,
          localIcon: 'material-symbols-light--modeling-sharp'
        }
      },
      {
        name: 'model-manage_train',
        path: '/model-manage/train',
        component: 'view.model-manage_train',
        meta: {
          title: 'model-manage_train',
          i18nKey: 'route.model-manage_train',
          icon: 'material-symbols:train-outline',
          localIcon: 'material-symbols--train-outline',
          order: 2
        }
      }
    ]
  },
  {
    name: 'target-monitor',
    path: '/target-monitor',
    component: 'layout.base',
    meta: {
      title: 'target-monitor',
      i18nKey: 'route.target-monitor',
      icon: 'mdi:target',
      localIcon: 'mdi--target',
      order: 4,
      hideInMenu: true
    },
    children: [
      {
        name: 'target-monitor_modelinference',
        path: '/target-monitor/modelinference',
        component: 'view.target-monitor_modelinference',
        meta: {
          title: 'target-monitor_modelinference',
          i18nKey: 'route.target-monitor_modelinference',
          icon: 'carbon:network-interface',
          localIcon: 'carbon--network-interface'
        }
      }
    ]
  },
  {
    name: 'thirdparty',
    path: '/thirdparty',
    component: 'layout.base',
    meta: {
      order: 6,
      title: 'thirdparty',
      i18nKey: 'route.thirdparty',
      localIcon: 'ThirdParty'
    },
    children: [
      {
        name: 'thirdparty_approve',
        path: '/thirdparty/approve',
        component: 'view.thirdparty_approve',
        meta: {
          title: 'thirdparty_approve',
          i18nKey: 'route.thirdparty_approve',
          order: 2,
          localIcon: 'ThirdParty_Approve'
        }
      },
      {
        name: 'thirdparty_assess',
        path: '/thirdparty/assess',
        component: 'view.thirdparty_assess',
        meta: {
          order: 4,
          title: 'ThirdParty_Assess',
          i18nKey: 'route.thirdparty_assess',
          localIcon: 'ThirdParty_Assess'
        }
      },
      {
        name: 'thirdparty_createtask',
        path: '/thirdparty/createtask',
        component: 'view.thirdparty_createtask',
        meta: {
          title: 'thirdparty_createtask',
          i18nKey: 'route.thirdparty_createtask'
        }
      },
      {
        name: 'thirdparty_info',
        path: '/thirdparty/info',
        component: 'view.thirdparty_info',
        meta: {
          title: 'ThirdParty_Info',
          i18nKey: 'route.thirdparty_info',
          activeMenu: 'thirdparty_assess',
          localIcon: 'ThirdParty_Report',
          hideInMenu: true
        }
      },
      {
        name: 'thirdparty_model',
        path: '/thirdparty/model',
        component: 'view.thirdparty_model',
        meta: {
          order: 2,
          title: 'ThirdParty_Model',
          i18nKey: 'route.thirdparty_model',
          localIcon: 'ThirdParty_Model',
          hideInMenu: true
        }
      },
      {
        name: 'thirdparty_modelmanage',
        path: '/thirdparty/modelmanage',
        component: 'view.thirdparty_modelmanage',
        meta: {
          title: 'thirdparty_modelmanage',
          i18nKey: 'route.thirdparty_modelmanage',
          localIcon: 'ThirdParty_ModelManage',
          order: 1
        }
      },
      {
        name: 'thirdparty_modeloperate',
        path: '/thirdparty/modeloperate',
        component: 'view.thirdparty_modeloperate',
        meta: {
          title: 'thirdparty_modeloperate',
          i18nKey: 'route.thirdparty_modeloperate',
          hideInMenu: true,
          localIcon: 'ThirdParty_ModelOperate',
          activeMenu: 'thirdparty_modelmanage'
        }
      },
      {
        name: 'thirdparty_operate',
        path: '/thirdparty/operate',
        component: 'view.thirdparty_operate',
        meta: {
          title: 'ThirdParty_Operate',
          i18nKey: 'route.thirdparty_operate',
          activeMenu: 'thirdparty_model',
          localIcon: 'ThirdParty_Operate',
          hideInMenu: true
        }
      },
      {
        name: 'thirdparty_prevassess',
        path: '/thirdparty/prevassess',
        component: 'view.thirdparty_prevassess',
        meta: {
          title: 'thirdparty_prevassess',
          i18nKey: 'route.thirdparty_prevassess',
          localIcon: 'model-manage_prevAssess',
          order: 1,
          hideInMenu: true
        }
      },
      {
        name: 'thirdparty_report',
        path: '/thirdparty/report',
        component: 'view.thirdparty_report',
        meta: {
          title: 'thirdparty_report',
          i18nKey: 'route.thirdparty_report',
          localIcon: 'ThirdParty_Report',
          order: 5
        }
      },
      {
        name: 'thirdparty_test',
        path: '/thirdparty/test',
        component: 'view.thirdparty_test',
        meta: {
          title: 'thirdparty_test',
          i18nKey: 'route.thirdparty_test',
          localIcon: 'ThirdParty_Test',
          order: 3,
          hideInMenu: true
        }
      }
    ]
  }
];
